const USER_REG = 'USER_REG';
const SAVE_SEARCH = 'SAVE_SEARCH';
const HANDLE_PAY = 'HANDLE_PAY';
const REMOVE_SCREEN_DATA = 'REMOVE_SCREEN_DATA';
export {USER_REG,SAVE_SEARCH,HANDLE_PAY,REMOVE_SCREEN_DATA};
